import {extendBaseTheme, theme as chakraTheme} from "@chakra-ui/react";

const {
    Accordion,
    Avatar,
    Alert,
    Button,
    Container,
    Heading,
    Drawer,
    CloseButton,
    Card,
    Spinner,
    Table,
    Input,
    Form,
    Select,
    Tag,
    Badge,
    Checkbox,
    FormError,
    FormLabel,
    Link,
    List,
    Tooltip,
    Menu,
    Stat,
    NumberInput,
    Modal,
    Code,
    Switch,
    Divider

} = chakraTheme.components

export const theme = extendBaseTheme({
    fonts: {
        heading: 'var(--font-rubik)',
        body: 'var(--font-rubik)',
    },
    components: {
        Accordion,
        Avatar,
        Alert,
        Heading,
        Button,
        Container,
        Drawer,
        CloseButton,
        Card,
        Spinner,
        Table,
        Input,
        Form,
        Select,
        Tag,
        Badge,
        Checkbox,
        FormError,
        FormLabel,
        Link,
        List,
        Tooltip,
        Menu,
        Stat,
        NumberInput,
        Modal,
        Code,
        Switch,
        Divider
    },
})